-- AlterTable
ALTER TABLE "HeatSourceFeature" ALTER COLUMN "minLng" DROP DEFAULT,
ALTER COLUMN "minLat" DROP DEFAULT,
ALTER COLUMN "maxLng" DROP DEFAULT,
ALTER COLUMN "maxLat" DROP DEFAULT;

-- AlterTable
ALTER TABLE "VegetationFeature" ALTER COLUMN "minLng" DROP DEFAULT,
ALTER COLUMN "minLat" DROP DEFAULT,
ALTER COLUMN "maxLng" DROP DEFAULT,
ALTER COLUMN "maxLat" DROP DEFAULT;
